def gerar_roteiro_video(tema):
    return (
        f"🎬 ROTEIRO DE VÍDEO V11 - {tema.upper()}\n\n"
        "Duração: 15 a 30 segundos\n\n"
        "Cena 1:\n"
        "Mostre o problema.\n"
        "Texto na tela: 'Sua marca ainda está invisível?'\n\n"
        "Cena 2:\n"
        "Mostre produtos personalizados.\n"
        "Texto: 'Camisetas, adesivos, canecas, panfletos e brindes.'\n\n"
        "Cena 3:\n"
        "Mostre detalhes do acabamento.\n"
        "Texto: 'Personalizado do seu jeito.'\n\n"
        "Cena 4:\n"
        "Mostre o resultado final.\n"
        "Texto: 'Sua ideia virou produto real.'\n\n"
        "Cena 5:\n"
        "Chamada final.\n"
        "Texto: 'Chama no direct e peça seu orçamento.'"
    )